//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jade_Dragon.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Connect : DbContext
    {
        public Connect()
            : base("name=Connect")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chitiethoadon> chitiethoadons { get; set; }
        public virtual DbSet<ErrorPay> ErrorPays { get; set; }
        public virtual DbSet<hoadon> hoadons { get; set; }
        public virtual DbSet<khachhang> khachhangs { get; set; }
        public virtual DbSet<khachsan> khachsans { get; set; }
        public virtual DbSet<khuvuc> khuvucs { get; set; }
        public virtual DbSet<Moc_Time> Moc_Time { get; set; }
        public virtual DbSet<phanhoi> phanhois { get; set; }
        public virtual DbSet<phong> phongs { get; set; }
        public virtual DbSet<PhongChat> PhongChats { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tinnhan> tinnhans { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<lichsu> lichsus { get; set; }
    }
}
