//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jade_Dragon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoSaoDanhGia
    {
        public long MaSoSao { get; set; }
        public Nullable<long> MaKhachSan { get; set; }
        public Nullable<long> MaKh { get; set; }
        public Nullable<long> SoSao { get; set; }
    
        public virtual khachhang khachhang { get; set; }
        public virtual khachsan khachsan { get; set; }
    }
}
